// #include "DynamicWIFIConnector/DynamicWIFIConnector.hpp"
// #include "Demo_3D_cube.hpp"
// #include "touchscreen_main.hpp"
#include "latihan1_main.hpp"
// #include "TouchScreen_Calibr_native/TouchScreen_Calibr_native.hpp"
// #include "aspect_kbv/aspect_kbv.hpp"
// #include "LCD_ID_readreg/LCD_ID_readreg.hpp"
// #include "testing_screen_mkv.hpp"